### ISSUE TITLE
Epic: support fractional CPU

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#101]
## Motivation

Free tier is currently defined as 0.25 CPU + 1 GB memory. We'd like to (a) move all users to VMs (which requires VMs with 0.25 CPU) and (b) _ideally_ allow scaling to/from the free tier limits of 0.25 CPU.

## DoD

Full support for fractional CPU allocations - in particular, allowing VMs to be created with 0.25 or 0.5 CPU, in addition to the typical integer scaling. The scheduler must appropriately handle bookkeeping for VMs with < 1 CPU.

As part of the implementation, we may also provide fractional CPUs above 1 - e.g. 11.5 CPU (instead of just integer number of CPUs when >= 1)

## Implementation ideas

There's a few possible ways of solving this. I think we've settled on doing this in NeonVM, not sure which of the 2nd or 3rd option.

1. Implement in the scheduler/autoscaler-agent via CPU overcommit.
2. Implement in NeonVM with K8s pod limits
3. Implement in NeonVM by running QEMU in a cgroup, inside the runner container

It's worth noting that option 2 would make it impossible for us to scale between CPU < 1 and CPU >= 1.

## Tasks

- [ ] Add support for fractional CPU in NeonVM
- [ ] Handle fractional CPU correctly in autoscaler-agent, scheduler (depends on NeonVM level of support)
- [ ] Enable fractional CPU for VMs in control plane/console

## Other related tasks and Epics

None

**Comment by sharnoff** [comment]
Fully done, in prod, etc. Should have been closed by #172, I think.
