### ISSUE TITLE
Epic: LFC-aware scaling follow-ups

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#1011]
## Motivation

With #1003, we have some minor known issues with the LFC-aware scaling implementation. These aren't enough to block merging, but we'd like to fix them eventually.

## Tasks

```[tasklist]
- [ ] Don't require exact 1-minute intervals for working set size metrics
- [ ] Trigger "stuck VMs" if core state is degraded (e.g., missing LFC metrics)
- [ ] Resurrect #737
- [ ] Make `lfcToMemoryRatio` required (or, emit warning if not set per VM)
```

## Other related tasks, Epics, and links

- #872
