### ISSUE TITLE
Epic: Create the pool of pre-allocated VMs

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/autoscaling#115]
### Motivation

To reduce start-up time for VMs (currently, it's ~4 seconds), we need to have several pre-warmed VMs and be able to change min/max boundaries at runtime.

### DoD
Start-up time for 99% of cases is < 1 sec

### Tasks:
* [x] https://github.com/neondatabase/autoscaling/pull/128 (includes handling runtime changes)
* [ ] https://github.com/neondatabase/cloud/pull/4741
* [x] https://github.com/neondatabase/autoscaling/issues/77

### Related epics/tasks/PRs: 
- neondatabase/neon#3610
- neondatabase/cloud#4433

**Comment by ololobus** [comment]
I don't think that we have to do it specifically for VMs only. There are at least two things that prevent doing it only on the autoscaler / neonvm side.

1. Compute versions, they are picked based on storage node versions, so only control-plane knows which version of the pre-created compute is needed. After storage release there always will be pre-created computes left with stale version, so control-plane needs to tear them down and spawn fresh ones.

2. `compute_ctl` needs JWT and id (`compute_id`) to be able to get spec from the control-plane. These two are also known to the control-plane only, and future compute_id<->endpoint_id binding too.

Thus, as I imagined and discussed it with @tychoish and @kelvich primarily, pool of pre-created 'whatever' (pods, VMs or any other custom resource in the future) is maintained by the control-plane. From compute we only need an interface to 'wake it up' and notify that it now serves some particular timeline. I added some PoC `compute_ctl` code in this PR https://github.com/neondatabase/neon/pull/3923

So the only required part from the autoscaler perspective is:

> be able to change min/max boundaries at runtime

And as we discussed with @sharnoff, we will likely need to switch to using labels / annotations for that, since this is usually the only thing one can change on k8s objects without re-creation / restart.

**Comment by vadim2404** [comment]
we discussed this item with you and it requires some on our side as well, therefore the epic is created.

> be able to change min/max boundaries at runtime
If it's enough, then who will be against it? :) 

> That said, I don't think that this target is realistic for a first iteration. Something like p90 or even p80 is more realistic, as any really huge spike from Hasura will likely hit k8s node autoscaler and p99 will ~20s-1min

I don't think that we need to stop after the first iteration. The ultimate goal is to have a really quick start-up for computes. Then, I don't want to discount the ultimate goal from the very beginning.

**Comment by sharnoff** [comment]
Was going to unassign myself because it seemed like the remaining work is in https://github.com/neondatabase/cloud/pull/4741, but given this:

> > That said, I don't think that this target is realistic for a first iteration. Something like p90 or even p80 is more realistic, as any really huge spike from Hasura will likely hit k8s node autoscaler and p99 will ~20s-1min
>
> I don't think that we need to stop after the first iteration. The ultimate goal is to have a really quick start-up for computes. Then, I don't want to discount the ultimate goal from the very beginning.

I added #77 to the task list, and am keeping myself assigned :)

However: I think the DoD does not match the issue title, so one of them should probably change.

**Comment by ololobus** [comment]
@sharnoff am I right that we can now change autoscaling limits on NeonVM without restart?

**Comment by sharnoff** [comment]
In theory we can, but there's still some bugs that makes it unusable in practice (#249, #252). Happy to prioritize those if it'd be useful. So far, my understanding was that the compute pool would just be creating VMs with their target sizes for now.
