### ISSUE TITLE
Epic: Deploy NeonVM and autoscaling in all regions

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/autoscaling#118]
### Motivation
We need to prepare our production environment to enable autoscaling for the whole user base.

### Tasks
* [x] Deploy NeonVM in us-west-2
* [x] Deploy Autoscaling in us-west-2
* [x] Enable Autoscaling for users in us-west-2
* [x] Deploy NeonVM in us-east-1
* [x] Deploy Autoscaling in us-east-1
* [x] Enable autoscaling for users in us-east-1

**Comment by sharnoff** [comment]
Deployed the components to us-east-1 and us-west-2, not yet enabled for users so I added those bullet points.

ref https://neondb.slack.com/archives/C03F5SM1N02/p1689919510993619
