### ISSUE TITLE
Epic: make autoscaling production-ready

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#2]
This is a collection of tasks from this repo & others that I'm _pretty_ sure will be required.  

**This does not include required tasks to get VMs & autoscaling working on staging.**

If there's something missing, feel free to add it to the appropriate task group.

## DoD

All non-optional tasks implemented and questions resolved.

Optional tasks would be good to have implemented, but are not strictly necessary for deploying to production.

## Tasks — `autoscaling` (this repo!)

- [x] https://github.com/neondatabase/autoscaling/pull/1
- [x] https://github.com/neondatabase/autoscaling/pull/4
  - [x] after: Support safe `autoscaler-agent` restart
    - Implemented by a combination: #8, #51
  - [x] after: #29
- [ ] Decide on logging story for scheduler plugin / `autoscaler-agent`
- [x] #8 — Communicate planned upscale/downscale to VM
  - [ ] this _must_ be authenticated
- [x] #30 - Support high memory (or: low memory) signals from the VM — and _probably_ don't scale down below current usage (see: "Further questions", "What happens if...")
  - note: as implemented, this PR prevents scaling down below current usage.
- [x] https://github.com/neondatabase/autoscaling/pull/47 — Update Neon file cache size on upscale/downscale
- [ ] https://github.com/neondatabase/autoscaling/issues/93
- [ ] Emit error(s) when total resource requests from pods we didn't schedule is greater than amount of unschedulable "system reserved" resources
  - Technically would be warnings according to the error handling RFC, but this is high-severity. 
- [ ] #81
- [x] #82
- https://github.com/neondatabase/autoscaling/issues/101
- [x] Integrate autoscaling with metrics collection / billing
  - [x] https://github.com/neondatabase/autoscaling/pull/43 (1/2)
  - [x] https://github.com/neondatabase/autoscaling/pull/49 (2/2)

---

- [ ] _optional_: Support changing VM limits without restarting `autoscaler-agent`
  - ~~probably best to switch `autoscaler-agent` to daemonset first~~ _done_
- [x] _optional_: https://github.com/neondatabase/autoscaling/pull/76 
  - [ ] _optional_: Provide separate tool to analyze this state
- [ ] _optional_: Scheduler live config updates
- [ ] _optional_: `autoscaler-agent` live config updates
- [ ] _optional_: Migrate away from under-utilized nodes to allow cluster autoscaler to remove them.
- [ ] _optional_: Add disk as resource type (required for handling local filesystem cache)
  - [ ] _optional_: Do we also need high disk usage (or: low disk usage) signals, like memory?

## Tasks — `neonvm`

- [x] Add Multus CNI support (https://github.com/neondatabase/neonvm/pull/34)
- [x] Implement VM migration (https://github.com/neondatabase/neonvm/pull/26, https://github.com/neondatabase/neonvm/pull/27)
- [ ] Ensure that ARM works
- [x] https://github.com/neondatabase/autoscaling/issues/97
  - related but not required: #12
- [ ] _optional_: Handle disk scaling (pending design work)

## Tasks — `neon` and `neondatabase/postgres`

- [x] https://github.com/neondatabase/neon/pull/2622
  - [x] ~~Resize cache when decreasing disk size?~~ Should be handled by VM informant
  - [x] Report disk usage with/without cache (so we can resize)
- [ ] _optional_: Finalize decision on `shared_buffers`
- [ ] _optional_: Report when e.g. vacuum is running, so it doesn't influence scaling decisions

## Tasks — `cloud`

- [ ] _optional_: Update NeonVM resource limits (if compute active) when endpoint limits change

## Tasks — console

- [ ] _optional_: Live view of current resource allocation
  - There's some neat options here where the `autoscaler-agent` could report the reason for scaling decisions and we display that here (e.g. "high load, wanted more CPU", "low load, but high memory usage is preventing downscale")

## Tasks — infra team

I don't know what, yet. If anyone on the infra team has ideas, it would be helpful to add them here to replace this paragraph. (see also: "What's required for sentry integration?")

## Further questions

- [ ] Can node resource limits change at runtime?
- [ ] What happens if memory is scaled down below current usage? (e.g. can this kill postmaster?)
- [ ] How do we handle VM migration failure?
  - [ ] What are possible failure causes?
- [ ] How can we minimize downtime during scheduler upgrades?
- [ ] What's required for sentry integration?

## Other related tasks and Epics

* https://github.com/neondatabase/cloud/issues/1651

**Comment by sharnoff** [comment]
Marked disk scaling as optional to reflect the outcome of our sync earlier this week.

**Comment by stepashka** [comment]
shall we close this @vadim2404 ?

**Comment by yaoyinnan** [comment]
@stepashka @vadim2404 Can the current autoscaling be used for production? I currently don't see documentation for deploying PostgreSQL's K8s with Neon storage layer components (Safekeeper, Pageserver), and the cluster topology cannot be configured in Autoscaling. Is there any relevant information? Please provide me with as much information as possible. Thanks.

**Comment by vadim2404** [comment]
We already use it in production. About documentation, yes, indeed, we need more cover in regard to the corresponding deployment. And one hidden component stays behind https://console.neon.tech/ this domain, which actually does the whole orchestration.
