### ISSUE TITLE
Epic: Be more careful about network connections from VMs

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#413]
## User stories

As we work towards moving autoscaling away from its prototype-y days of yore, and towards a robust production system, we should pay more attention to areas that are needlessly careless about security.

## DoD

- No autoscaling-specific network connections originating _from_ VMs
- Ability to restrict outbound / inbound network connections for a VM
- Outbound / inbound network connections _are_ restricted for VMs

This is part 1 of 2, for security-related improvements for autoscaling & NeonVM. Part 2 is [here](https://github.com/neondatabase/autoscaling/issues/414).

## Contributing Epics & tasks

```[tasklist]
- [ ] agent <-> informant communication should be over websocket initiated by autoscaler-agent
- [ ] https://github.com/neondatabase/autoscaling/pull/433
- [ ] Control plane should set iptables rules for VMs (once supported)
```

See also:

- #402
- https://github.com/neondatabase/cloud/pull/5890

## Related Projects and Epics

- https://github.com/neondatabase/neon_roadmap/issues/122
- #414

**Comment by sharnoff** [comment]
This was completed with #447 and neondatabase/cloud#6316; added #442 and neondatabase/cloud#6587 because they were also relevant.
