### ISSUE TITLE
Epic: Further network hardening

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#414]
## User stories

As a follow-up to #413, we should also _generally_ make sure that if a hypothetical attacker _did_ have access to our network, they'd have a hard time messing with our systems.

Realistically, there's more important areas of security work to get to first. For now, this epic exists to write down the ideas _somewhere_ to make sure they're tracked. Some of the pieces here are actually quite difficult to set up.

## DoD

- All connections between autoscaling components are authenticated.

This is part 2 of 2, for security-related improvements for autoscaling & NeonVM. Part 1 is [here](https://github.com/neondatabase/autoscaling/issues/413).

## Contributing Epics & tasks

```[tasklist]
- [ ] #413 
- [ ] Access to VM's QEMU should be restricted to neonvm-controller
- [ ] Scheduler plugin should authenticate autoscaler-agent connections
- [ ] plugin + agent "dump state" and pprof endpoints should be authenticated
- [ ] agent -> informant connections should be authenticated by informant
```

## Related Projects and Epics

- https://github.com/neondatabase/neon_roadmap/issues/122
- #413
