### ISSUE TITLE
Epic: Migrate users to VMs in Asia

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/autoscaling#419]
- [ ] Migrate first 10% of projects in Asia
- [ ] Migrate next 20% of projects in Asia
- [ ] Migrate next 30% of projects in Asia
- [ ] Migrate next 40% of projects in Asia

**Comment by vadim2404** [comment]
this week: 20%
@vadim2404 to talk to support team about users' notification (pods -> VMs migration)

**Comment by vadim2404** [comment]
migrate another 30% of the users base this week

**Comment by sharnoff** [comment]
Because the rollout is not region-by-region (and instead overlapping somewhat), I've edited this epic to more closely track the entire "migration to VMs" effort.

**Comment by sharnoff** [comment]
Plan for this week:
- Leave `ap-southeast-1` alone, to keep the load split until we can change the default provisioner + disable k8s-pod for new projects/endpoints.
- Migrate 20% each of `eu-central-1` and `us-east-2`
- Migrate 10% each of `us-east-1` and `us-west-2` (two batches of 5% each)

**Comment by sharnoff** [comment]
This week:

* Leave `ap-southeast-1` alone still
* Migrate 30% each of `eu-central-1` and `us-east-2`
* Migrate 20% each of `us-east-1` and `us-west-2`

**Comment by sharnoff** [comment]
This week:

* Leave `ap-southeast-1`, `eu-central-1` alone
* Migrate as many as possible in `us-east-2` (limit 50% of remaining)
  * Still only 10% of free tier is VMs there
* Migrate 30% each of `us-east-1` and `us-west-2`

**Comment by sharnoff** [comment]
This week:

* Migrate all remaining free-tier idle endpoints in `us-east-1` and `us-west-2`
* Also, migrate any idle free-tier endpoints in other regions that weren't migrated the first time around, or have since been created.

**Comment by stepashka** [comment]
hi team, is tehre a grafana dashboard by any chance showing the status of the migration?

**Comment by sharnoff** [comment]
Not currently. Here's something that's a bit hacky, but should give the general idea: https://neonprod.grafana.net/goto/axPTbL4SR?orgId=1

**Comment by vadim2404** [comment]
Previous week:
didn't migrate because of the issue with `cache=unsafe`

This week:
Ideally - 20% in the beginning of week, 30% in the end of week
