### ISSUE TITLE
v0.18.0 post-deploy issue tracker

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#550]
There were lots of big changes, so naturally some issues on staging were expected. This github issue exists to track the things found and their resolution

```[tasklist]
# Released as v0.18.0-patch1
- [ ] https://github.com/neondatabase/autoscaling/pull/551
- [ ] https://github.com/neondatabase/autoscaling/pull/552
- [ ] https://github.com/neondatabase/autoscaling/pull/553
```

```[tasklist]
# Released as v0.18.0-patch2
- [ ] https://github.com/neondatabase/autoscaling/pull/558
- [ ] https://github.com/neondatabase/autoscaling/pull/556
- [ ] https://github.com/neondatabase/autoscaling/pull/557
- [ ] https://github.com/neondatabase/autoscaling/pull/560
```

Going to leave open for a while either way, until this has been sitting on staging for a while.
