### ISSUE TITLE
Epic: Unify vm-builders

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#577]
## Motivation

The current vm-builder situation is messy and inflexible:
1. We have two copies of _roughly_ the same code
2. Components like vector, pgbouncer, and postgres_exporter are all installed and configured in vm-builder
    - Updating the version or config requires (a) a new autoscaling release, _and then_ (b) new compute images — whereas the control plane can immediately change configs or versions for regular pods

We also have a very hacky solution for process lifecycle management during shutdown implemented in #525 (see also #529).

## DoD

- [x] Unified vm-builder and vm-builder-generic
- [x] No postgres- or Neon-specific details in vm-builder

## Implementation ideas

(moved to #835)

## Tasks

```[tasklist]
- [ ] https://github.com/neondatabase/autoscaling/pull/600
- [ ] https://github.com/neondatabase/neon/pull/5783
```

## Other related tasks, Epics, and links

- #578

**Comment by sharnoff** [comment]
Moved the "containers" part to a separate issue in #835; closing this because the first half has been completed for a while.
