### ISSUE TITLE
Epic: investigate VM compute cold start time and ideally decrease it

### ISSUE THREAD

**Issue by kelvich** [neondatabase/autoscaling#711]
## Motivation

We have pools of pre-created computes to amortize k8s api latency and vm boot latency. This is how the current boot time distribution looks like:
<img width="914" alt="image" src="https://github.com/neondatabase/autoscaling/assets/284219/d5a51f1f-681c-4ab3-8010-5acbe2ff720b">
in case of pool miss end user will experience bigger start latency. Since we are moving everything to VMs soon it would be good to improve VM start speed.

## DoD

Understand where time is actually spend during the boot. Fireckracker start times are below 1s, so we should understand what are the main reasons for our start times to be slower and whether there are any easy improvements that we can do right away.

So for this task DoD is a text explaining the difference in boot times and list of suggestion on how to improve them without losing ability to scale and live migrate VM's.

## Implementation ideas

* start firecracker with their default kernel/image
* start firecracker with our image -- will it be slower? how much?
* look into qemu-microvm 

## Tasks

```[tasklist]
- [x] Preliminary logs assessment
- [ ] https://github.com/neondatabase/autoscaling/issues/747
- [ ] https://github.com/neondatabase/autoscaling/issues/759
- [ ] https://github.com/neondatabase/autoscaling/issues/860
```

## Other related tasks, Epics, and links
Part of the https://github.com/neondatabase/company_projects/issues/130

**Comment by cicdteam** [comment]
@kelvich 
>Fireckracker start times are below 1s

I'd like to clarify what exactly we mean by `start time`. Time to boot the kernel and start the init process (pid 1)? Our VMs do this in about 0.4s ([proof link](https://neonprod.grafana.net/goto/lBGzHFdSg?orgId=1)), which I don't think is the major overhead that VMs have. Need to understand why startup processes inside a VM are slower than in a Pod.

**Comment by shayanh** [comment]
Earlier, I drew a workflow diagram to show what happens when we create a VM resource object. There other steps before getting into Kubernetes API server, which Stas has mentioned in [his Slack message](https://neondb.slack.com/archives/C03TN5G758R/p1703235575205199).

<img width="2242" alt="image" src="https://github.com/neondatabase/autoscaling/assets/1623278/6aaf658a-6aed-4950-9f1c-2c72f8e55ed5">

Based on @cicdteam's comment, this is probably due to the communication between the components involved in the process. Though still we have to investigate why `k8s-neonvm - no pool` is much slower than `k8s-pod no pool`. 

As something for the future, to deal with this set of issues and generally improve the observability in our system, it may worth to invest in distributed tracing platforms, such as [Jaeger](https://www.jaegertracing.io/).

**Comment by cicdteam** [comment]
@shayanh 

The workflow diagram for the pod provisioner is almost the same. Just `Deployment` instead of `neonvm` and no step named `neonvm-runner` (where we run QEMU).

We can try a test like this - run NGINX as k8s deployment and poll it to see when it responds to an http request. Do the same with a neonvm and compare results.  I think the latencies will be almost the same.

**Comment by Omrigan** [comment]
I took a particularly long start_compute[1], taking 36.5s and investigated it:
56:54 - operation's created_at [1]
56:55 - Creating a new Pod [2]
56:56 - Started container init-rootdisk [2]
56:58 - Created container sysct [2]
56:59 - Started container sysctl [2]
57:04 - Created container compute-init [2]
57:16 - Started container compute-init [2]
57:17 - Created container neonvm-runner [2]
57:18 - Started container neonvm-runner [2]
57:18 - First dmesg entry [3]
57:19 - Error opening config file \"postgres_exporter.yml\" [3] (is this a separate issue?)
57:19 - database system is ready to accept connections [3]
57:20 - compute start finished [3]
57:20 - connection authorized [3]

... (investigate deeper)

57:25 -  Plug one more Memory module into VM [2] 
57:30 - updated_at [1]

57:34 - sending powerdown command to QEMU

Some on-the-spot conclusions:
1. This validates the claim that QEMU start is negligible
2. Userspace inside the VM also starts fast
3. A main bulk of time is spend starting auxiliary containers

Further actions:
1. Verify if this picture reproduces in multiple cases
2. Investigate deeper what happens between 57:20 (compute start finished) and 57:30 (VM is ready to accept connections). Although even the reduced time is quite high (26s vs full 36s)
3. Look deeper into those auxiliary containers

[1]: https://console.stage.neon.tech/admin/regions/console/operations/b2e755d4-b571-46b7-8180-743c4e65de2f
[2]: https://neonprod.grafana.net/d/cc4f137c-f2fd-4e18-a00a-c92234e3b33a/neon-logs-autoscaling?orgId=1&var-environment=dev%7Cstaging&var-metricsource=HUNg6jvVk&var-logsource=xHHYY0dVz&var-cluster=All&var-loglevel=All&var-node=All&var-agentsubsystem=All&var-schedsubsystem=All&var-event_component=All&var-vm=compute-misty-hall-16416010&var-parsed=yes
[3]: https://neonprod.grafana.net/d/IJSLHBOnk/neon-logs-compute-nodes-by-compute-id?orgId=1&var-datasource=xHHYY0dVz&var-compute=compute-misty-hall-16416010&var-search=&var-exclude=substing%20to%20exclude&from=now-30m&to=now

**Comment by Omrigan** [comment]
Startup times by different provisioner.
```
 provisioner | bucket |   range   | freq |              bar
-------------+--------+-----------+------+--------------------------------
 k8s-neonvm  |      3 | [7,9)     |   86 | ■■■■
 k8s-neonvm  |      4 | [9,12)    |  469 | ■■■■■■■■■■■■■■■■■■■■■
 k8s-neonvm  |      5 | [12,15)   |  170 | ■■■■■■■■
 k8s-neonvm  |      6 | [15,18)   |   91 | ■■■■
 k8s-neonvm  |      7 | [18,21)   |   96 | ■■■■
 k8s-neonvm  |      8 | [21,24)   |   82 | ■■■■
 k8s-neonvm  |      9 | [24,27)   |   88 | ■■■■
 k8s-neonvm  |     10 | [27,30)   |   61 | ■■■
 k8s-neonvm  |     11 | [30,33)   |   54 | ■■
 k8s-neonvm  |     12 | [33,36)   |   47 | ■■
 k8s-neonvm  |     13 | [36,39)   |   51 | ■■
 k8s-neonvm  |     14 | [39,42)   |   30 | ■
 k8s-neonvm  |     15 | [42,45)   |   30 | ■
 k8s-neonvm  |     16 | [45,83)   |   79 | ■■■■
 k8s-pod     |      2 | [3,6)     |  120 | ■■■■■
 k8s-pod     |      3 | [6,9)     |  677 | ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
 k8s-pod     |      4 | [9,12)    |  181 | ■■■■■■■■
 k8s-pod     |      5 | [12,15)   |   65 | ■■■
 k8s-pod     |      6 | [15,18)   |   36 | ■■
 k8s-pod     |      7 | [18,21)   |   12 | ■
 k8s-pod     |      8 | [21,24)   |   13 | ■
 k8s-pod     |      9 | [24,27)   |    7 |
 k8s-pod     |     13 | [36,37)   |    1 |
 k8s-pod     |     16 | [46,1110) |    8 |
             |      1 | [2,3)     |   56 | ■■
             |      2 | [3,6)     |  188 | ■■■■■■■■
             |      3 | [6,9)     |   10 |
```
<details>
<summary>
Query
</summary>

```sql
with histogram as (
   select width_bucket(startup_time, 0, 45, 15) as bucket,
          int4range(min(startup_time), max(startup_time), '[]') as range,
          count(*) as freq,
          provisioner
     from (
        select (extract(epoch from updated_at) - extract(epoch from created_at))::integer as startup_time,
                metadata->'compute_metadata'->>'provisioner' as provisioner
          from operations
         where action = 'start_compute'
           and metadata->'start_compute'->>'from_pool' = 'false'
           and operations.created_at > current_date - interval '24 hour'
      ) as subquery
 group by bucket, provisioner
 order by provisioner, bucket
)
 select provisioner, bucket, range, freq,
        repeat('■',
               (   freq::float
                 / max(freq) over()
                 * 30
               )::int
        ) as bar
   from histogram;
```
</details>

**Comment by Omrigan** [comment]
Another one:  https://console.neon.tech/admin/regions/console/operations/e1a18e48-7786-42df-a6b7-477e5df359a2

- 0:26 - created_at
- 0:47 - Creating a new Pod
- 0:53 - Created container compute-init
- 0:54 - Started container compute-init
- 1:11 - Created container neonvm-runner
- 1:12 - Started container neonvm-runner
- 1:16 - First dmesg entry
- 1:16 - compute start finished
- 1:27 - updated_at

**Comment by Omrigan** [comment]
Another one: https://console.neon.tech/admin/regions/console/operations/5195384a-c676-4bcb-b52d-d76b50244364

compute_id: compute-super-mountain-87037727

- 0:40 - created_at
- 0:52 - Creating a new Pod
- 1:03 - Started container neonvm-runner
- 1:11 - First dmesg entry
- 1:11 - compute start finished
- 1:10 - updated_at

This looks suspicious, as I'd expect `compute start finished` would be always before `updated_at`. Clock skew?

**Comment by Omrigan** [comment]
I would split the VM startup time into the following phases:
1. `Scheduler`: from `created_at` to `Creating a new Pod`
2. `Pod init`: from `Creating a new Pod` to `Started container neonvm-runner`
3. `Runner`: from `Started container neonvm-runner` to first dmesg entry
4. `Boot`: first dmesg entry to `compute start finished`
5. `Finalize`: from `compute start finished` to `updated_at`

Hypothesis to verify:
1. We don't need to optimize phase 5, as the compute is operational at the end of phase 4
2. Phases 3 and 4 take a relatively small amount of time (TODO: define p99 latency)
3. The largest offenders are phases 1 and 2

This analysis doesn't explain why `neonvm` take longer than `pods`. Doesn't it takes different steps to schedule and init pod?

We should ideally have the observability tooling to perform such analysis real-time.

**Comment by Omrigan** [comment]
https://console.neon.tech/admin/regions/console/operations/e7047e4b-c766-47b9-a1d9-379ae1fa0c42

```
15s:
1+2 -> 10
3+4 -> 1
5 -> 4
```

**Comment by sharnoff** [comment]
status: @Omrigan will try to reproduce, and go from there

**Comment by Omrigan** [comment]
https://console.neon.tech/admin/regions/console/operations/4861083c-dd0a-4ece-a58e-1bbd3671f513

Here I compare  log entries between one start_compute and [the one I investigated before](https://github.com/neondatabase/autoscaling/issues/711#issuecomment-1877400784). `prev` means how long it took for `compute-misty-hall-16416010` between a particular 

 - (Phase 1 starts) `created_at` -> 0:45
 - (Phase 2 starts) `Creating a new Pod` -> 1:00 (took 15s, prev 1s)
 - `Started container init-rootdisk` -> 1:06 (took 6s, prev 1s)
 - `Created container sysctl` -> 1:22 (took 16s, prev 2s)
 - `Started container compute-init` -> 1:24 (took 2s, prev 18s)
 - (Phase 3 starts)  `Started container neonvm-runner` -> 1:25 (took 1s, prev 2s)
 - (Phase 4 starts) first dmesg entry -> 1:27 (took 2s, prev 0s)
 - (Phase 5 starts) `compute start finished` -> 1:30 (took 3s, prev 2s)
 - `updated_at` -> 1:39

Judging by this, there is no pattern in which a particular container starts slower. Therefore, the possible the delay originates from slowness of `k8s'`s  state update.

**Comment by Omrigan** [comment]
Let's take now the `k8s-pod` compute and see what happens there

https://console.neon.tech/admin/regions/console/operations/dd7df822-94f0-4582-aa5e-36ad6df808ec

 - (Phase 1 starts) `created_at` -> 0:03
 - Not sure where to get `k8s-pod`s logs from k8s internals (like  `Neon/Logs/ Autoscaling`)
 -  (Phase 4 starts)` `logging and tracing started` (first message from inside the pod) -> 0:06 [2] 
 - Then we have 42s between these log lines:
```	
2024-01-15 13:00:07.133 UTC [1] LOG process up: PgBouncer 1.21.0, libevent 2.1.12-stable (epoll), adns: c-ares 1.17.1, tls: OpenSSL 1.1.1w  11 Sep 2023

2024-01-15T13:00:49.658783Z  INFO start_compute:prepare_pgdata: checking pg_hba.conf
```
 - (Phase 5 starts) `compute start finished` -> 0:49
 - `updated_at` -> 0:50 

So `phase 5` is 1s, far less than we had for VMs.

Therefore, two possible explanations of why VM startup time is more, than pods:
1. `k8s-pod` provisioner has less containers, therefore k8s has less work to do (less reconciliation loops?)
2. The way of reporting of `start_compute`'s end time might differ, meaning we actually have a working compute earlier than recorded in operation's `updated_at`.   

[2]: https://neonprod.grafana.net/d/IJSLHBOnk/neon-logs-compute-nodes-by-compute-id?orgId=1&var-datasource=grafanacloud-logs&var-compute=compute-steep-fire-36306150&var-search=&var-exclude=%28libpagestore%29%7C%28.%2A.go%29%7C%28LOG%20s-%29%7C%28LOG%20C%29%7C%28LOG%20S-%29%7C%28serving%20%2Fstatus%29%7C%28connection%20received%7Cauthorized%7Cauthenticated%29%7C%28OpenTelemetry%29%7C%28ProcessStandbyReply%29%7C%28STATEMENT:%20%20START_REPLICATION%29%7C%28watch:%29%7C%28start_monitor:%29%7C%28skipping%20missing%29&from=now-24h&to=now

**Comment by Omrigan** [comment]
I've managed to set up a local compute: [compute-polished-poetry-10720110](http://localhost:60000/admin/regions/console/computes/compute-polished-poetry-10720110)

 - (P1) 37:09 `created_at`
 - (P2) 37:14 `Creating a new Pod`
 - 37:18 `Created container compute-init`
 - (P3) 37:19 (Started container neonvm-runner)
 - (P4) 37:19 first dmesg entry 
 - (P5) 37:20 `compute start finished`
 - 37:21 updated_at

**Comment by Omrigan** [comment]
The startup time became more noisy.

How it was at issue creation:
 <img width="914" alt="image" src="https://github.com/neondatabase/autoscaling/assets/284219/d5a51f1f-681c-4ab3-8010-5acbe2ff720b">

How it is now:
![screenshot-2024-01-17_19-41-58_293250049](https://github.com/neondatabase/autoscaling/assets/2663743/ee4c2ccb-2242-47df-b7d1-9fb899e075eb)


Also, these are apparently p50 images. on p99 there is even more noise:

![screenshot-2024-01-17_19-43-48_335864019](https://github.com/neondatabase/autoscaling/assets/2663743/ef2bee2b-6b7f-480e-8abc-8147ac4155de)

**Comment by sharnoff** [comment]
Status: To  try a solution, will merge two init containers into one (#747) - @Omrigan will write a script to create a lot of new VMs to stress-test. Maybe look at `cloudbench` / start lots of computes at a time on staging via API

**Comment by shayanh** [comment]
A nit on https://github.com/neondatabase/autoscaling/issues/711#issuecomment-1889219969:

> 1. Scheduler: from created_at to Creating a new Pod

In this phase actually the scheduler is not involved at all. Once the pod is created after this phase, scheduler receives it in its queue and binds it to a node.

The scheduling actually happens in the second phase:
> 2. Pod init: from Creating a new Pod to Started container neonvm-runner

**Comment by Omrigan** [comment]
> A nit on [#711 (comment)](https://github.com/neondatabase/autoscaling/issues/711#issuecomment-1889219969):
> 
> > 1. Scheduler: from created_at to Creating a new Pod
> 
> In this phase actually the scheduler is not involved at all. Once the pod is created after this phase, scheduler receives it in its queue and binds it to a node.

What happens in this phase then?

**Comment by shayanh** [comment]
The following happens in this phase:
1. Control plane sends a request to k8s API server to create a VM object.
2. K8s API server validates the objects itself
3. K8s API server calls NeonVM controller webhook to do a different sort of validation.
4. K8s API server stores the object in etcd.
5. NeonVM controller notices the new VM object via its watch process.
6. NeonVM controller reconciles the VM object: first changes the status to Pending and then created the runner pod (where you see the `Creating a new Pod` in the logs).

Maybe you can name it `Create` or `Initial` phase.

**Comment by Omrigan** [comment]
Future situation best to be tracked with [this graph](https://neonprod.grafana.net/d/adg35sd2lo2kgc/neon-autoscaling-vm-cold-start?orgId=1&from=1703277310626&to=1711053310626&viewPanel=4)
