### ISSUE TITLE
Epic: Create an SLO dashboard for autoscaling

### ISSUE THREAD

**Issue by stradig** [neondatabase/autoscaling#867]
## Motivation
While huge outages that are visible to customers always draw a lot of attention, there can also be many smaller outages that might run under the radar. Still, with many smaller outages, the product's reputation can erode. Therefore, such a series should also be brought to the team's attention, and measures should be taken to address those.

An SLO dashboard like https://neonprod.grafana.net/d/ade9uqqklodmob/neon-control-plane-slos?orgId=1&var-datasource=ZNX49CDVz&var-service=control-plane&var-slo=start_compute_latency_p90_under_1s&var-region=All&var-sli_window=5m can be useful for that. It shows the SLO in a rolling 30 day window and also how much of a defined SLO budget has been used so far. 

If a budget has been exhausted some action should be taken (TBD) like freezing releases, doing extra care for releases or PRs, etc.

## DoD
A set of SLOs and associated budgets has been defined for the team's projects. A dashboard similar to the above exists tracking those. Not that this is internal, only. 

## Tasks

```[tasklist]
- [ ] Define a list of Service Level Indicators (SLIs) to observe.
- [ ] Define a list of Service Level Objectives (SLOs) for those SLIs with associated budgets (together with the product team).
- [ ] Implement an SLO dashboard
```
